version: '3.8'

services:
  ocr:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu] 